### ISSUE TITLE
[Windows] preprocess_element widget appears to hang when stdout is too large

### ISSUE THREAD

**Issue by astroowen** [dmbaturin/soupault#20] opened 2021-02-02 18:50 UTC
This is a very weird issue, I have to say. I'm writing a blog post in a Markdown file, converting it to HTML with pandoc, and pre-processing it with a python script, using the `preprocess_element` widget in my soupault.conf. The issue I've come across is that when the .md file is too large, Soupault hangs after receiving the stdout from the python program. I know that it's soupault hanging and not the python script itself, because you can run it alone and it exits fine.

I've attached a working example: [site.test.zip](https://github.com/dmbaturin/soupault/files/5913633/site.test.zip). To repliacte:

- download, extract the site.test folder into any directory with write access
- open cmd.exe or PowerShell in the directory, and execute soupault.exe*
- observe that it hangs after displaying the data that was sent to the python script
- open index.md and delete any one single character
- save, then run soupault.exe again
- observe that Soupault completes the build process and doesn't hang anymore

The file index.md is a 10,618 byte UTF-8 text file. It's literally right on the boundary of what will pass through. There are some unicode characters in it, like an emoji, but it doesn't have to be one of those that you remove - just backspace any character at all and with 10,617 bytes it now works.

To verify that the python script works on its own, run (in PowerShell, for the use of the pipe) this command:

    pandoc --quiet -s -f markdown-hard_line_breaks+header_attributes --template "./body-class" .\index.md | .\figure-thoughts.py

from the site.test directory. It will print the output of the file to stdout as expected. Note that to make a minimal working example I removed all the code from the script that actually modifies the text (it was just some string.replace() and stuff), but it made no difference to the issue here.

I'm running Soupault 2.4.0 on Windows 10. I don't know if this also happens on Linux.

*You can also run the build-one.bat script but it assumes where Soupault is installed

**Comment by dmbaturin** [comment] 2021-02-02 19:45
A curious issue indeed. It doesn't happen on Linux with your test site, and I couldn't reproduce it with even larger amounts of data, so the issue seems to be Windows-specific, but I wonder where it's coming from. I'll try to debug it.

Out of curiosity, what the real Python script does? I may be able to suggest a workaround until the issue is fixed, but without knowing what it does, it's easy to make a wrong/useless suggestion.

**Comment by Cycloneblaze** [comment] 2021-02-02 19:51
[Yeah, here's the full file.](https://github.com/dmbaturin/soupault/files/5914097/figure-thoughts.zip) Feel free to test with that.

**Comment by astroowen** [comment] 2021-02-02 19:52
[Here's the full file; feel free to test with that.](https://github.com/dmbaturin/soupault/files/5914105/figure-thoughts.zip)

**Comment by dmbaturin** [comment] 2021-02-02 20:20
While the bug remains a bug and I'm going to look into it, there's a much better way to do what you want to do. You are essentially parsing HTML with regular expressions, while you have access to the element tree. I've attached a version I think is much more idiomatic. 
[site-test-lua.zip](https://github.com/dmbaturin/soupault/files/5914236/site-test-lua.zip)


New file: `figure-thoughts.lua`:

```lua
function add_chirality_class(index, elem)
  if (index % 2) == 0 then
    class = "right"
  else
    class = "left"
  end

  HTML.add_class(elem, class)
end

figures = HTML.select(page, "figure")
Table.iter(add_chirality_class, figures)

function make_image_link(img)
  src = HTML.get_attribute(img, "src")
  if not src then
    return nil
  end
  link = HTML.create_element("a")
  HTML.set_attribute(link, "href", src)
  -- Insert the link into the page,
  -- just before the <img> we are processing
  -- (could as well be insert_after)
  HTML.insert_before(img, link)

  -- Make the <img> a child node of the link we've just created
  HTML.append_child(link, img)
end

imgs = HTML.select(page, "img")
Table.iter_values(make_image_link, imgs)
```

In `soupault.conf` instead of your preprocess-element widget:

```
[plugins.figure-thoughts]
  file = "figure-thoughts.lua"

# Pages can be further processed with "widgets"
        
[widgets.figure-thoughts]
  widget = "figure-thoughts"

```

**Comment by astroowen** [comment] 2021-02-02 20:41
Yeah, I knew I could write a widget to modify Soupault directly to do what I wanted to do, but I don't already know Lua, so I did the immediately-faster thing.

I swapped out the preprocess-element widget for the one you just wrote on my production site, and it digested the full blog post just fine. It seems that the former widget is where the problem lies. Actually, that means I can continue and publish my post in the meantime, so thanks for that 😁

**Comment by dmbaturin** [comment] 2021-02-02 21:06
Another advantage of a Lua plugin is that it will work with any formatting, while the original script makes an assumption that a `<figure>` tag is always on its own line...

On a side note, would you mind the site added to the [users page](https://soupault.app/users/)?

**Comment by astroowen** [comment] 2021-02-02 21:42
> On a side note, would you mind the site added to the users page?

Not at all! Use [owen.higgins.id](https://owen.higgins.id/) (if it was not obvious from the header)

**Comment by dmbaturin** [comment] 2021-02-04 16:56
Do you know anyone versed in Windows debugging? I fear we'll have to find someone because my own knowledge is exhausted.

All I could find is that it fails at _writing_ data to the script's stdin. From my attempts to mess with WinDbg, it hangs on `NtWriteFile` that never returns. 

Perhaps there's something about Windows I/O that I'm missing. I'll try to experiment with it myself, but I'm not sure where to look.

**Comment by dmbaturin** [comment] 2021-02-10 17:17
@astroowen There's one thing I missed about your script, that it iterates over `fileinput.input()` and outputs lines _as it reads them_. The issue here is that soupault first sends the complete input to the program and closes its input pipe, then waits for its output.

Since pipes are blocking, if a program doesn't keep reading until EOF, there will be a deadlock. On Windows, the buffer size is 4096 bytes, so a deadlock can come much sooner. Modifying your original script to do `sys.stdin.readlines()` and iterating over the lines solves the issue.

Changing the protocol to a "read a line, write a line" will break programs that are designed to read and write at once, and all programs that aren't line oriented at all, so that isn't an option.

On UNIX, the traditional solution is to create a fork of the parent process to handle the _writing_ to the child, while the original process keeps reading. Windows doesn't have a `fork()` system call though, so this won't work as a cross-platform solution (besides, forking can be quite resource-intensive and the typical input size isn't large enough to warrant that).

I've documented the pitfall here: https://soupault.app/reference-manual/#external-program-behavior

Let me know if you have any questions.

**Comment by astroowen** [comment] 2021-02-10 19:15
This makes sense to me. I'm not currently using this widget for anything like this, but if I do, I'll come back and make comments. Thanks for looking into it!

(Also, incidentally I do not know any Windows debugging experts)

**Comment by dmbaturin** [comment] 2021-02-11 05:22
Ok, I'm closing this issue then. If anything, feel free to reopen or make a new one.

**Closed by dmbaturin** 2021-02-11 05:22 UTC
